---
# Source: gitops-microservices-helm-template/templates/deploy-template/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cost-estimator-calc-service-ddedb69eb7b6586760b63ee461eade2a62083d07
  namespace: hcb-edmlprvdraaece-pdev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cost-estimator-calc-service-ddedb69eb7b6586760b63ee461eade2a62083d07
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization:  80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
